Added Social Media Icons
smilegupta/portfolio-smilegupta pull request #5
Opened 2020-12-08 10:54 UTC by chinmaym07

Hey @smilegupta Please Review . 

![Screen Shot 2020-12-08 at 16 21 56](https://user-images.githubusercontent.com/44670961/101474939-bd99e800-3971-11eb-9a33-adef976e7a6b.png)
![Screen Shot 2020-12-08 at 16 06 00](https://user-images.githubusercontent.com/44670961/101474950-bffc4200-3971-11eb-9738-4a9460e6f3a0.png)
![Screen Shot 2020-12-08 at 16 05 46](https://user-images.githubusercontent.com/44670961/101474958-c1c60580-3971-11eb-8c71-212e2df55804.png)

2020-12-08 16:26 UTC, smilegupta commented on index.html
> +        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
Font awesome is not consumed in the project right,  wont it be better if we remove the cdn just to make code look clean

2020-12-08 16:32 UTC, smilegupta requested changes
Couple of suggestions, in now a days people also tend to have codepen and codesandbox also included on the profile. It will add the look and feel of the portfolio too.  
@chinmaym07 A suggestion from my end. As market demands to standout.

2020-12-08 21:03 UTC, chinmaym07 commented
Hey @smilegupta  I have done the changes .Please Review.

![Screen Shot 2020-12-09 at 02 31 10](https://user-images.githubusercontent.com/44670961/101541087-e7c9c500-39c6-11eb-985c-7ed87775cd6c.png)
![Screen Shot 2020-12-09 at 02 31 00](https://user-images.githubusercontent.com/44670961/101541091-e8faf200-39c6-11eb-9ee6-8954963a9733.png)

2020-12-08 21:36 UTC, smilegupta approved these changes

2020-12-08 21:36 UTC, merged

2020-12-08 21:37 UTC, smilegupta commented
Good Work Done! You right awesome code.

2020-12-09 07:37 UTC, chinmaym07 commented
> Good Work Done! You right awesome code.

Thankyou So much @smilegupta :grinning: :+1: